"""Dodat enum za podtipove uredjaja

Revision ID: 7615cd8d2240
Revises: d7b9a46c1132
Create Date: 2025-07-22 22:06:50.025824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7615cd8d2240'
down_revision = 'd7b9a46c1132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uredjaji', schema=None) as batch_op:
        batch_op.alter_column('podtip',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('split_sistem', 'cileri', 'centralna_klima', 'toplotne_pumpe', 'kanalska_klima', 'klima_komora', 'pokretna_klima', 'klima_ormar', 'prozorska_klima', 'vrf_sistemi', 'frizideri', 'ta_pec', 'grejalice', 'kotlovi', 'panelni_radijatori', 'radijatori', name='podtip_uredjaja'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uredjaji', schema=None) as batch_op:
        batch_op.alter_column('podtip',
               existing_type=sa.Enum('split_sistem', 'cileri', 'centralna_klima', 'toplotne_pumpe', 'kanalska_klima', 'klima_komora', 'pokretna_klima', 'klima_ormar', 'prozorska_klima', 'vrf_sistemi', 'frizideri', 'ta_pec', 'grejalice', 'kotlovi', 'panelni_radijatori', 'radijatori', name='podtip_uredjaja'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
