"""story 2.4

Revision ID: d7b9a46c1132
Revises: 
Create Date: 2025-07-21 18:54:19.476626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7b9a46c1132'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('objekti', schema=None) as batch_op:
        batch_op.alter_column('radna_jedinica_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('pravna_lica', schema=None) as batch_op:
        batch_op.alter_column('pib',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=False)
        batch_op.alter_column('mb',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=False)

    with op.batch_alter_table('prostorije', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numericka_oznaka', sa.String(length=50), nullable=True))
        batch_op.alter_column('naziv',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('broj')

    with op.batch_alter_table('radne_jedinice', schema=None) as batch_op:
        batch_op.alter_column('telefon',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radne_jedinice', schema=None) as batch_op:
        batch_op.alter_column('telefon',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('prostorije', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broj', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('naziv',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('numericka_oznaka')

    with op.batch_alter_table('pravna_lica', schema=None) as batch_op:
        batch_op.alter_column('mb',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('pib',
               existing_type=sa.String(length=9),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('objekti', schema=None) as batch_op:
        batch_op.alter_column('radna_jedinica_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
